version: '3.2'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
# Below line was commented out because it causes error in container start up
#    command: --serviceExecutor adaptive
